[Interface]
Address = 20.20.20.2/24
PrivateKey = 6Mm3OkTQoCekHlI24DYrW9P8NKg9L8mRvWSerferZH4=
ListenPort = 51820
Table = 123
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i wg2 -j ACCEPT
PostUp = iptables -A FORWARD -o wg2 -j ACCEPT
#PreUp = ip rule add iif wg2 table 123 priority 456
#PreUp = iptables -t nat -A POSTROUTING -o wg2 -j MASQUERADE
#PostDown = ip rule del iif wg2 table 123 priority 456

[Peer]
PublicKey = yAq35PEekG2imnqU3r2IR2urMeJStda4b6Wh2CYbxCY=
AllowedIPs = 20.20.20.1/32
PersistentKeepalive = 25

[Peer]
PublicKey = bH1IsQlTt1Je9kAgd7QlxBzE+KeUkFNDvmzB6UDlPko=
AllowedIPs = 0.0.0.0/0
Endpoint = 10.0.20.102:51820
PersistentKeepalive = 25
