[Interface]
Address = 20.20.20.3/24
PrivateKey = 2J3YgghlO7jERE7HNqw2ugVRlmL0LVSWH+IGTBedxU0=
ListenPort = 51820
PreUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i wg2 -j ACCEPT
PostDown = iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE
#PostUp = iptables -A FORWARD -i wg2 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens18 -j MASQUERADE
#PostDown = iptables -D FORWARD -i wg2 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens18 -j MASQUERADE

[peer]
PublicKey = FVC77PqtK7L0AScEsFIA7/2fHKYyUZ2nTCoBRd6r3k8=
AllowedIPs = 20.20.20.2/32
persistentKeepalive = 25
